graph TD;
    v1/secret/data/aws/access_key-->$VAULT_SERVER;
    v1/secret/data/aws/secret_key-->$VAULT_SERVER;
    $VAULT_SERVER-->vault_provider;
    $VAULT_TOKEN-->vault_provider;
    vault_provider-->access_key;
    vault_provider-->secret_key;
    access_key-->aws_provider;
    secret_key-->aws_provider;
    region-->aws_provider;
    aws_provider-->aws_instance;
    var.my_ami-->aws_instance;
    var.my_subnet-->aws_instance;
    var.my_SGs-->aws_instance;
    var.my_key-->aws_instance;
    var.my_route53_zone_id-->aws_instance;
    aws_instance-->jenkins;
    aws_instance-->imap
    imap-->s3-bucket
